
services:
  postgres:
    container_name: postgres
    image: postgres:16
    restart: always
    env_file:
      - ./server/.env
    environment:
      - POSTGRES_USER=${POSTGRES_USER_NAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATA_BASE}
      - POSTGRES_DATA_BASE${POSTGRES_DATA_BASE}
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - ./init-db/init.sql:/docker-entrypoint-initdb.d/0_init.sql
      - postgres-datavolume:/var/lib/postgresql/data
    networks:
      - internalnet



  server:
    container_name: server
    image: mysql:8.0
    env_file:
      - ./server/.env
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    volumes:
      - server-datavolume:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  server-datavolume:
    